policies:
  # The following policies are designed to work from GitHub action workflows.
  # This means that before running any Updatecli command, we need the two following environment variables set:
  # 
  #   GITHUB_TOKEN: Set to a personal access token
  #   GITHUB_ACTOR: Set to the username associated with the GITHUB_TOKEN
  # 
  # Instruction to retrieve your PAT is documented on https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  - name: Handle releasepost
    policy: ghcr.io/salasberryfin/rancherlabs-policies/releasepost:0.1.0@sha256:dbc4a04e02f81a791f229b2cb572da3a06dd70009c967be9813af359c4ec5277
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/turtles.yaml
